<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NuGet.Packaging" Version="7.9.0" />
    <PackageReference Include="NuGet.Protocol" Version="7.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BulkyBook.DataAccess\BulkyBook.DataAccess.csproj" />
    <ProjectReference Include="..\BulkyBook.Models\BulkyBook.Models.csproj" />
    <ProjectReference Include="..\BulkyBook.Utility\BulkyBook.Utility.csproj" />
  </ItemGroup>

</Project>
